=== FPersch/Palladio-Core-PCM/obsolete/Palladio.Performance.Helge/config/XmlSeffParser.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ServiceEffectAutomaton (statelist,inputlist,transitionlist)>
<!ELEMENT statelist (state*)>
<!ATTLIST statelist
	startstate CDATA #REQUIRED
>
<!ELEMENT state (name,time_consumption*)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST state
	isFinalState CDATA #IMPLIED
	>
<!ELEMENT inputlist (input*)>
<!ELEMENT input (#PCDATA)>
<!ELEMENT transitionlist (transition*)>
<!ELEMENT transition (sourcestate, input, destinationstate, probability?, time_consumption+)>
<!ELEMENT sourcestate (#PCDATA)>
<!ELEMENT destinationstate (#PCDATA)>
<!ELEMENT probability (#PCDATA)>
<!ELEMENT time_consumption EMPTY>
<!ATTLIST time_consumption
	percentile CDATA #REQUIRED
	time 	     CDATA #REQUIRED
>

=== FPersch/Palladio-Core-PCM/obsolete/Palladio.Performance.Helge/TestData/Seff.xml
<?xml version="1.0"?>
<!DOCTYPE WebserverMeasure SYSTEM "XmlSeffParser.dtd">
<ServiceEffectAutomaton>
  <statelist startstate="7101">
    <state isFinalState="true">
      <name>7102</name>
      <time_consumption percentile="100" time="1000" />
    </state>
    <state>
      <name>7101</name>
      <time_consumption percentile="90" time="1000" />
      <time_consumption percentile="100" time="2000" />
    </state>
  </statelist>
  <inputlist>
    <input>IWebserverConfiguration_get_DocumentRoot</input>
  </inputlist>
  <transitionlist>
    <transition>
      <sourcestate>7101</sourcestate>
      <input>IWebserverConfiguration_get_DocumentRoot</input>
      <destinationstate>7102</destinationstate>
      <probability>1</probability>
      <time_consumption percentile="90" time="1000" />
      <time_consumption percentile="90" time="2000" />
      <time_consumption percentile="90" time="3000" />
      <time_consumption percentile="90" time="4000" />
      <time_consumption percentile="90" time="5000" />
      <time_consumption percentile="90" time="6000" />
      <time_consumption percentile="100" time="7000" />
    </transition>
  </transitionlist>
</ServiceEffectAutomaton>

=== FPersch/Palladio-Core-PCM/trunk/Patterns/Cache/SEA_cache.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ServiceEffectAutomaton SYSTEM "XmlSeffParser.dtd">
<ServiceEffectAutomaton>
        <statelist startstate="CacheInvoked">
        <state>
                <name>CacheInvoked</name>
                <time_consumption percentile="100" time="0"></time_consumption>
        </state>
        <state isFinalState="true">
                <name>finalstate</name>
        </state>
        </statelist>
        <inputlist>
                <input>InvokeService</input>
                <input>NoInvocation</input>
        </inputlist>
        <transitionlist>
                        <transition>
                                <sourcestate>CacheInvoked</sourcestate>
                                <input>InvokeService</input>
                                <destinationstate>finalstate</destinationstate>
                                <probability>0.5</probability>
                                <time_consumption percentile="40" time="50"></time_consumption>
                                <time_consumption percentile="60" time="80"></time_consumption>
                                <time_consumption percentile="100" time="100"></time_consumption>
                        </transition>
        <transition>
                <sourcestate>CacheInvoked</sourcestate>
                <input>NoInvocation</input>
                <destinationstate>finalstate</destinationstate>
                <probability>0.5</probability>
                <time_consumption percentile="100" time="0"></time_consumption>
        </transition>
        </transitionlist>
</ServiceEffectAutomaton>

=== FPersch/Palladio-Core-PCM/obsolete/Palladio.Performance.Helge/XmlSeffParser/src/Test/ExampleSeff3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ServiceEffectAutomaton SYSTEM "XmlSeffParser.dtd">
<ServiceEffectAutomaton>
        <statelist startstate="s1">
        <state>
                <name>s1</name>
                <time_consumption percentile="100" time="100"></time_consumption>
        </state>
        <!--state isFinalState="true"-->
        <state>
                <name>s2</name>
                <time_consumption percentile="100" time="100"></time_consumption>
        </state>
        <state>
                <name>s3</name>
                <time_consumption percentile="100" time="100"></time_consumption>
	</state>
        <state>
                <name>s4</name>
                <time_consumption percentile="100" time="100"></time_consumption>
	</state>
	<state>
                <name>s5</name>
                <time_consumption percentile="100" time="100"></time_consumption>
	</state>
	<state isFinalState="true">
                <name>s6</name>
                <time_consumption percentile="100" time="100"></time_consumption>
        </state>
        </statelist>
        <inputlist>
                <input>a</input><input>b</input><input>c</input><input>d</input>
		<input>e</input>
		<input>f</input>
		<input>g</input>
        </inputlist>
        <transitionlist>
                        <transition>
                                <sourcestate>s1</sourcestate>
                                <input>a</input>
                                <destinationstate>s2</destinationstate>
                                <probability>1</probability>
                                <time_consumption percentile="40" time="500"></time_consumption>
                                <time_consumption percentile="75" time="1000"></time_consumption>
                                <time_consumption percentile="100" time="2000"></time_consumption>
                        </transition>
        <transition>
                <sourcestate>s2</sourcestate>
                <input>b</input>
                <destinationstate>s2</destinationstate>
                <probability>0.72</probability>
                                <time_consumption percentile="50" time="1500"></time_consumption>
                                <time_consumption percentile="75" time="2000"></time_consumption>
                                <time_consumption percentile="100" time="4000"></time_consumption>
        </transition>
        <transition>
                <sourcestate>s3</sourcestate>
                <input>c</input>
                <destinationstate>s2</destinationstate>
                <probability>1</probability>
                                <time_consumption percentile="50" time="1500"></time_consumption>
                                <time_consumption percentile="75" time="2000"></time_consumption>
                                <time_consumption percentile="100" time="4000"></time_consumption>
        </transition>
        <transition>
                <sourcestate>s2</sourcestate>
                <input>d</input>
                <destinationstate>s3</destinationstate>
                <probability>0.08</probability>
                <time_consumption percentile="50" time="400"></time_consumption>
                <time_consumption percentile="75" time="1000"></time_consumption>
                <time_consumption percentile="100" time="2000"></time_consumption>
        </transition>
        <transition>
                <sourcestate>s2</sourcestate>
                <input>e</input>
                <destinationstate>s4</destinationstate>
                <probability>0.2</probability>
                <time_consumption percentile="70" time="500"></time_consumption>
                <time_consumption percentile="100" time="1500"></time_consumption>
        </transition>
        <transition>
                <sourcestate>s4</sourcestate>
                <input>f</input>
                <destinationstate>s5</destinationstate>
                <probability>1</probability>
                <time_consumption percentile="70" time="500"></time_consumption>
                <time_consumption percentile="100" time="1500"></time_consumption>
        </transition>
        <transition>
                <sourcestate>s5</sourcestate>
                <input>g</input>
                <destinationstate>s6</destinationstate>
                <probability>1</probability>
                <time_consumption percentile="70" time="500"></time_consumption>
                <time_consumption percentile="100" time="1500"></time_consumption>
        </transition>
        </transitionlist>
</ServiceEffectAutomaton>
