=== FPersch/Palladio-Core-PCM/Palladio.Performance.Helge/TestData/WebserverMeasure.dtd
<?xml version="1.0" encoding="UTF-8"?><!--DTD generated by XMLSPY v2004 rel. 4 U (http://www.xmlspy.com)--><!ELEMENT CallLevel (#PCDATA)><!ELEMENT CallNumber (#PCDATA)><!ELEMENT CallTime (#PCDATA)><!ELEMENT CallerID (#PCDATA)><!ELEMENT ClassName (#PCDATA)><!ELEMENT ExecutionTime (#PCDATA)><!ELEMENT InterfaceName (#PCDATA)><!ELEMENT MethodName (#PCDATA)><!ELEMENT Palladio.Webserver.BibTeXProvider.BibTeXProvider_IHTTPRequestProcessor_HandleRequest (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.BibTeXProvider.BibTeXProvider_IHTTPRequestProcessor_HandleRequest	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.BibTeXProvider.BibTexDB_IBibTexDB_Search (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.BibTeXProvider.BibTexDB_IBibTexDB_Search	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.BibTeXProvider.BibTexDB_IBibTexDB_SearchAllEntries (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.BibTeXProvider.BibTexDB_IBibTexDB_SearchAllEntries	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.BibTeXProvider.BibTexDB_IBibTexDB_set_ConnectionString (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.BibTeXProvider.BibTexDB_IBibTexDB_set_ConnectionString	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_GetMimeTypeFor (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_GetMimeTypeFor	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ConfigFilesPath (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ConfigFilesPath	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_DebugFile (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_DebugFile	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_DefaultFileNames (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_DefaultFileNames	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_DefaultMimeType (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_DefaultMimeType	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_DocumentRoot (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_DocumentRoot	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ListenIP (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ListenIP	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ListeningPorts (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ListeningPorts	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_LogFile (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_LogFile	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.ConfigReader.XMLConfigReader_IConfigReader_ReadConfiguration (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.ConfigReader.XMLConfigReader_IConfigReader_ReadConfiguration	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.Dispatcher.DefaultDispatcher_IDispatcher_Start (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.Dispatcher.DefaultDispatcher_IDispatcher_Start	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.Dispatcher.DefaultDispatcher_IDispatcher_Stop (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.Dispatcher.DefaultDispatcher_IDispatcher_Stop	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.Dispatcher.PortListener_IPortListener_StartListen (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.Dispatcher.PortListener_IPortListener_StartListen	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.Dispatcher.PortListener_IPortListener_get_Address (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.Dispatcher.PortListener_IPortListener_get_Address	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.Dispatcher.PortListener_IPortListener_get_Port (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.Dispatcher.PortListener_IPortListener_get_Port	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.Dispatcher.PortListener_IPortListener_set_IsRunning (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.Dispatcher.PortListener_IPortListener_set_IsRunning	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.DynamicFileProvider.DynamicFileProvider_IHTTPRequestProcessor_HandleRequest (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.DynamicFileProvider.DynamicFileProvider_IHTTPRequestProcessor_HandleRequest	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.HTTPRequestParser.HTTPRequestParser_IRequestParser_HandleRequest (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.HTTPRequestParser.HTTPRequestParser_IRequestParser_HandleRequest	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_BuildCompletePath (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_BuildCompletePath	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_GetFileMimeTypeFor (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_GetFileMimeTypeFor	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_OpenFile (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_OpenFile	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_SendContentDataToClient (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_SendContentDataToClient	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_SendContentToClient (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_SendContentToClient	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_SendHTTPError (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_SendHTTPError	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_SendHTTPHeader (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_SendHTTPHeader	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.SimpleTemplateFileProvider.SimpleTemplateFileProvider_IHTTPRequestProcessor_HandleRequest (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.SimpleTemplateFileProvider.SimpleTemplateFileProvider_IHTTPRequestProcessor_HandleRequest	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.StaticFileProvider.StaticFileProvider_IHTTPRequestProcessor_HandleRequest (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.StaticFileProvider.StaticFileProvider_IHTTPRequestProcessor_HandleRequest	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor_IWebserverMonitor_FinishWriteAccess (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor_IWebserverMonitor_FinishWriteAccess	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor_IWebserverMonitor_InitializeWriteAccess (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor_IWebserverMonitor_InitializeWriteAccess	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor_IWebserverMonitor_WriteLogEntry (CallNumber, CallLevel, CallerID, ClassName, InterfaceName, MethodName, CallTime, ReturnTime, ExecutionTime, ThreadID)><!ATTLIST Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor_IWebserverMonitor_WriteLogEntry	CallNumber ID #REQUIRED	CallerID IDREF #IMPLIED	Calls IDREFS #IMPLIED><!ELEMENT ReturnTime (#PCDATA)><!ELEMENT RunID (#PCDATA)><!ELEMENT ThreadID (#PCDATA)><!ELEMENT WebserverMeasure (RunID | Palladio.Webserver.ConfigReader.XMLConfigReader_IConfigReader_ReadConfiguration | Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ConfigFilesPath | Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_DebugFile | Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_LogFile | Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor_IWebserverMonitor_InitializeWriteAccess | Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor_IWebserverMonitor_WriteLogEntry | Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ListenIP | Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ListeningPorts | Palladio.Webserver.Dispatcher.DefaultDispatcher_IDispatcher_Start | Palladio.Webserver.BibTeXProvider.BibTeXProvider_IHTTPRequestProcessor_HandleRequest | Palladio.Webserver.BibTeXProvider.BibTexDB_IBibTexDB_Search | Palladio.Webserver.BibTeXProvider.BibTexDB_IBibTexDB_SearchAllEntries | Palladio.Webserver.BibTeXProvider.BibTexDB_IBibTexDB_set_ConnectionString | Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_GetMimeTypeFor | Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_DefaultFileNames | Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_DefaultMimeType | Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_DocumentRoot | Palladio.Webserver.Dispatcher.DefaultDispatcher_IDispatcher_Stop | Palladio.Webserver.Dispatcher.PortListener_IPortListener_StartListen | Palladio.Webserver.Dispatcher.PortListener_IPortListener_get_Address | Palladio.Webserver.Dispatcher.PortListener_IPortListener_get_Port | Palladio.Webserver.Dispatcher.PortListener_IPortListener_set_IsRunning | Palladio.Webserver.DynamicFileProvider.DynamicFileProvider_IHTTPRequestProcessor_HandleRequest | Palladio.Webserver.HTTPRequestParser.HTTPRequestParser_IRequestParser_HandleRequest | Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_BuildCompletePath | Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_GetFileMimeTypeFor | Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_OpenFile | Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_SendContentDataToClient | Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_SendContentToClient | Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_SendHTTPError | Palladio.Webserver.HTTPRequestProcessor.DefaultHTTPRequestProcessorTools_IHTTPRequestProcessorTools_SendHTTPHeader | Palladio.Webserver.SimpleTemplateFileProvider.SimpleTemplateFileProvider_IHTTPRequestProcessor_HandleRequest | Palladio.Webserver.StaticFileProvider.StaticFileProvider_IHTTPRequestProcessor_HandleRequest | Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor_IWebserverMonitor_FinishWriteAccess)+>

=== FPersch/Palladio-Core-PCM/Palladio.Performance.Helge/WebserverSeff/src/Test/TestData/Measure7.xml
<?xml version="1.0"?>
<!DOCTYPE WebserverMeasure SYSTEM "WebserverMeasure.dtd">
<WebserverMeasure>
  <RunID>7</RunID>
  <Palladio.Webserver.ConfigReader.XMLConfigReader_IConfigReader_ReadConfiguration CallNumber="_1">
    <CallNumber>1</CallNumber>
    <CallLevel>1</CallLevel>
    <CallerID>0</CallerID>
    <ClassName>Palladio.Webserver.ConfigReader.XMLConfigReader</ClassName>
    <InterfaceName>IConfigReader</InterfaceName>
    <MethodName>ReadConfiguration</MethodName>
    <CallTime>8044325607</CallTime>
    <ReturnTime>8044422966</ReturnTime>
    <ExecutionTime>97359</ExecutionTime>
    <ThreadID>1</ThreadID>
  </Palladio.Webserver.ConfigReader.XMLConfigReader_IConfigReader_ReadConfiguration>
  <Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ConfigFilesPath CallNumber="_2">
    <CallNumber>2</CallNumber>
    <CallLevel>1</CallLevel>
    <CallerID>0</CallerID>
    <ClassName>Palladio.Webserver.ConfigReader.WebserverConfiguration</ClassName>
    <InterfaceName>IWebserverConfiguration</InterfaceName>
    <MethodName>get_ConfigFilesPath</MethodName>
    <CallTime>8045469236</CallTime>
    <ReturnTime>8045469684</ReturnTime>
    <ExecutionTime>448</ExecutionTime>
    <ThreadID>1</ThreadID>
  </Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ConfigFilesPath>
  <Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ConfigFilesPath CallNumber="_3">
    <CallNumber>3</CallNumber>
    <CallLevel>1</CallLevel>
    <CallerID>0</CallerID>
    <ClassName>Palladio.Webserver.ConfigReader.WebserverConfiguration</ClassName>
    <InterfaceName>IWebserverConfiguration</InterfaceName>
    <MethodName>get_ConfigFilesPath</MethodName>
    <CallTime>8046052204</CallTime>
    <ReturnTime>8046052216</ReturnTime>
    <ExecutionTime>12</ExecutionTime>
    <ThreadID>1</ThreadID>
  </Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ConfigFilesPath>
  <Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_DebugFile CallNumber="_5" CallerID="_4">
    <CallNumber>5</CallNumber>
    <CallLevel>2</CallLevel>
    <CallerID>4</CallerID>
    <ClassName>Palladio.Webserver.ConfigReader.WebserverConfiguration</ClassName>
    <InterfaceName>IWebserverConfiguration</InterfaceName>
    <MethodName>get_DebugFile</MethodName>
    <CallTime>8046572938</CallTime>
    <ReturnTime>8046603443</ReturnTime>
    <ExecutionTime>30505</ExecutionTime>
    <ThreadID>1</ThreadID>
  </Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_DebugFile>
  <Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_LogFile CallNumber="_6" CallerID="_4">
    <CallNumber>6</CallNumber>
    <CallLevel>2</CallLevel>
    <CallerID>4</CallerID>
    <ClassName>Palladio.Webserver.ConfigReader.WebserverConfiguration</ClassName>
    <InterfaceName>IWebserverConfiguration</InterfaceName>
    <MethodName>get_LogFile</MethodName>
    <CallTime>8046606869</CallTime>
    <ReturnTime>8046617354</ReturnTime>
    <ExecutionTime>10485</ExecutionTime>
    <ThreadID>1</ThreadID>
  </Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_LogFile>
  <Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor_IWebserverMonitor_InitializeWriteAccess CallNumber="_4" Calls="_5 _6">
    <CallNumber>4</CallNumber>
    <CallLevel>1</CallLevel>
    <CallerID>0</CallerID>
    <ClassName>Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor</ClassName>
    <InterfaceName>IWebserverMonitor</InterfaceName>
    <MethodName>InitializeWriteAccess</MethodName>
    <CallTime>8046569947</CallTime>
    <ReturnTime>8046622329</ReturnTime>
    <ExecutionTime>52382</ExecutionTime>
    <ThreadID>1</ThreadID>
  </Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor_IWebserverMonitor_InitializeWriteAccess>
  <Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor_IWebserverMonitor_WriteLogEntry CallNumber="_8" CallerID="_7">
    <CallNumber>8</CallNumber>
    <CallLevel>2</CallLevel>
    <CallerID>7</CallerID>
    <ClassName>Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor</ClassName>
    <InterfaceName>IWebserverMonitor</InterfaceName>
    <MethodName>WriteLogEntry</MethodName>
    <CallTime>8046626624</CallTime>
    <ReturnTime>8046629282</ReturnTime>
    <ExecutionTime>2658</ExecutionTime>
    <ThreadID>1</ThreadID>
  </Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor_IWebserverMonitor_WriteLogEntry>
  <Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor_IWebserverMonitor_WriteLogEntry CallNumber="_9" CallerID="_7">
    <CallNumber>9</CallNumber>
    <CallLevel>2</CallLevel>
    <CallerID>7</CallerID>
    <ClassName>Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor</ClassName>
    <InterfaceName>IWebserverMonitor</InterfaceName>
    <MethodName>WriteLogEntry</MethodName>
    <CallTime>8046629351</CallTime>
    <ReturnTime>8046630175</ReturnTime>
    <ExecutionTime>824</ExecutionTime>
    <ThreadID>1</ThreadID>
  </Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor_IWebserverMonitor_WriteLogEntry>
  <Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ListenIP CallNumber="_10" CallerID="_7">
    <CallNumber>10</CallNumber>
    <CallLevel>2</CallLevel>
    <CallerID>7</CallerID>
    <ClassName>Palladio.Webserver.ConfigReader.WebserverConfiguration</ClassName>
    <InterfaceName>IWebserverConfiguration</InterfaceName>
    <MethodName>get_ListenIP</MethodName>
    <CallTime>8046631123</CallTime>
    <ReturnTime>8046637566</ReturnTime>
    <ExecutionTime>6443</ExecutionTime>
    <ThreadID>1</ThreadID>
  </Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ListenIP>
  <Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ListeningPorts CallNumber="_11" CallerID="_7">
    <CallNumber>11</CallNumber>
    <CallLevel>2</CallLevel>
    <CallerID>7</CallerID>
    <ClassName>Palladio.Webserver.ConfigReader.WebserverConfiguration</ClassName>
    <InterfaceName>IWebserverConfiguration</InterfaceName>
    <MethodName>get_ListeningPorts</MethodName>
    <CallTime>8046640556</CallTime>
    <ReturnTime>8046661092</ReturnTime>
    <ExecutionTime>20536</ExecutionTime>
    <ThreadID>1</ThreadID>
  </Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ListeningPorts>
  <Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ListeningPorts CallNumber="_12" CallerID="_7">
    <CallNumber>12</CallNumber>
    <CallLevel>2</CallLevel>
    <CallerID>7</CallerID>
    <ClassName>Palladio.Webserver.ConfigReader.WebserverConfiguration</ClassName>
    <InterfaceName>IWebserverConfiguration</InterfaceName>
    <MethodName>get_ListeningPorts</MethodName>
    <CallTime>8046661145</CallTime>
    <ReturnTime>8046661186</ReturnTime>
    <ExecutionTime>41</ExecutionTime>
    <ThreadID>1</ThreadID>
  </Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ListeningPorts>
  <Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ListeningPorts CallNumber="_13" CallerID="_7">
    <CallNumber>13</CallNumber>
    <CallLevel>2</CallLevel>
    <CallerID>7</CallerID>
    <ClassName>Palladio.Webserver.ConfigReader.WebserverConfiguration</ClassName>
    <InterfaceName>IWebserverConfiguration</InterfaceName>
    <MethodName>get_ListeningPorts</MethodName>
    <CallTime>8046668669</CallTime>
    <ReturnTime>8046668753</ReturnTime>
    <ExecutionTime>84</ExecutionTime>
    <ThreadID>1</ThreadID>
  </Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ListeningPorts>
  <Palladio.Webserver.Dispatcher.DefaultDispatcher_IDispatcher_Start CallNumber="_7" Calls="_8 _9 _10 _11 _12 _13">
    <CallNumber>7</CallNumber>
    <CallLevel>1</CallLevel>
    <CallerID>0</CallerID>
    <ClassName>Palladio.Webserver.Dispatcher.DefaultDispatcher</ClassName>
    <InterfaceName>IDispatcher</InterfaceName>
    <MethodName>Start</MethodName>
    <CallTime>8046623311</CallTime>
    <ReturnTime>8046669236</ReturnTime>
    <ExecutionTime>45925</ExecutionTime>
    <ThreadID>1</ThreadID>
  </Palladio.Webserver.Dispatcher.DefaultDispatcher_IDispatcher_Start>
  <Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ListenIP CallNumber="_16" CallerID="_15">
    <CallNumber>16</CallNumber>
    <CallLevel>2</CallLevel>
    <CallerID>15</CallerID>
    <ClassName>Palladio.Webserver.ConfigReader.WebserverConfiguration</ClassName>
    <InterfaceName>IWebserverConfiguration</InterfaceName>
    <MethodName>get_ListenIP</MethodName>
    <CallTime>8046710513</CallTime>
    <ReturnTime>8046710569</ReturnTime>
    <ExecutionTime>56</ExecutionTime>
    <ThreadID>3</ThreadID>
  </Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ListenIP>
  <Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ListenIP CallNumber="_18" CallerID="_14">
    <CallNumber>18</CallNumber>
    <CallLevel>2</CallLevel>
    <CallerID>14</CallerID>
    <ClassName>Palladio.Webserver.ConfigReader.WebserverConfiguration</ClassName>
    <InterfaceName>IWebserverConfiguration</InterfaceName>
    <MethodName>get_ListenIP</MethodName>
    <CallTime>8046715582</CallTime>
    <ReturnTime>8046715635</ReturnTime>
    <ExecutionTime>53</ExecutionTime>
    <ThreadID>2</ThreadID>
  </Palladio.Webserver.ConfigReader.WebserverConfiguration_IWebserverConfiguration_get_ListenIP>
  <Palladio.Webserver.WebserverMonitor.DefaultWebserverMonitor_IWebserverMonitor_WriteLogEntry CallNumber="_17" CallerID="_15">
    <CallNumber>17</CallNumber>
