=== FPersch/Palladio-Core-PCM/trunk/Config/BibTeXProviderXML.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Config (DataSource, DatabaseName, DatabaseTableName, SearchedBibTeXFieldNames, HandledFileTypes, ErrorMessageOnConnectionProblems)>
<!ATTLIST Config
	xmlns:xsi CDATA #REQUIRED
	xsi:noNamespaceSchemaLocation CDATA #REQUIRED
>

<!ELEMENT DataSource EMPTY>
<!ATTLIST DataSource
	Name CDATA #REQUIRED
>

<!ELEMENT DatabaseName EMPTY>
<!ATTLIST DatabaseName
	 Name CDATA #REQUIRED
>

<!ELEMENT DatabaseTableName EMPTY>
<!ATTLIST DatabaseTableName
	 Name CDATA #REQUIRED
>

<!ELEMENT SearchedBibTeXFieldNames (FieldName+)>

<!ELEMENT FieldName EMPTY>
<!ATTLIST FieldName
	 Name CDATA #REQUIRED
>

<!ELEMENT HandledFileTypes (File*)>
<!ELEMENT File EMPTY>
<!ATTLIST File
	 Extension CDATA #REQUIRED
>

<!ELEMENT ErrorMessageOnConnectionProblems EMPTY>
<!ATTLIST ErrorMessageOnConnectionProblems
	 Message CDATA #REQUIRED
>

=== FPersch/Palladio-Core-PCM/trunk/Config/BibTeXProviderXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "BibTeXProviderXML.dtd">
<Config xmlns:xsi="Webserver" xsi:noNamespaceSchemaLocation="BibTeXProviderXML.dtd">
	
	<!--Name of the Database-Server. For the use with a local database this is be identically to the host-name of your computer.-->
	<DataSource Name="kuser_mobile" />

	<!--Name of the Database, where the BibTeX-Entries are saved. "initial catalog" in the connection-string.-->	
	<DatabaseName Name="BibTeX" />
	
	<!--Name of the Table, where the BibTeX-Entries are saved.-->	
	<DatabaseTableName Name="BibTeX" />
	
	<!--Security-Settings that is used. Default value is "SSPI".-->
	<DatabaseIntegratedSecurity Value="SSPI" />
	
	<!--Set the persist security info-value for the database connection string. The default value is "False".-->
	<DatabasePersistSecurityInfo Value="False" />
	
	<!--This field allows to define additional database-connection-values. The default value is "". Please keep in mind that
		integrated security, data source, persist security info and, initial catalog are already set above. The string must have
		the form ";[key1]=[value1]; .. ;[key1]=[value1];". Note the ";" as the very first position.-->
	<DatabaseAdditionalConnectionString Value="" />
	
	<!--The following FieldNames are taken into consideration to search for BibTeX-Entries in the DB. This means
		if one of the following FieldNames occours in the post-request it is used as a part of the search-request.
		Other FieldNames will be ignored until they are set in this file.-->	
	<SearchedBibTeXFieldNames>
			<FieldName Name="author" />
			<FieldName Name="title" />
			<FieldName Name="publisher" />
			<FieldName Name="year" />
	</SearchedBibTeXFieldNames>

	<!--The File-Extensions the BibTeXProvider shall handle to display search results. The files do not have to
		exist in the filesystem. The BibTeXProvider produces XHTML-Tables to represent the answer.-->
	<HandledFileTypes>
			<File Extension=".bibhtml" />
	</HandledFileTypes>

	<!--If no connection can be established to the Database-Server this message is displayed to the users.-->
	<ErrorMessageOnConnectionProblems Message="Error: could not connect to the databaseserver." />
		
</Config>
